server:
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.yupi.yupaobackend.mybatis.entity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yupao
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update